In [1]:
import numpy as np

# 1-Write a NumPy program to test whether none of the elements of a given array is zero.

In [25]:
def test(lst):
    count = 0
    for val in lst:
        if val != 0:
            count += 1
        if count == len(lst):
            return True
        else:
            return False
x = np.array([1, 3, 4, 5])
y = np.array([0, 2, 3, 6])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is zero:")
print(test(x))
print('#'*50)
print("Original array:")
print(y)
print('#'*50)
print("Test whether any of the elements of a given array is zero:")
print(test(y))
print('#'*50)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))
print('#'*50)
x = np.array([0, 0, 0, 0])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is zero:")
print(np.all(x))

Original array:
[1 3 4 5]
Test whether any of the elements of a given array is zero:
False
##################################################
Original array:
[0 2 3 6]
##################################################
Test whether any of the elements of a given array is zero:
False
##################################################
Test whether any of the elements of a given array is non-zero:
True
##################################################
Original array:
[0 0 0 0]
Test whether any of the elements of a given array is zero:
False


# 2-Write a NumPy program to test whether any of the elements of a given array is non-zero

In [26]:
def test(lst):
    count = 0
    for val in lst:
        if val != 0:
            count += 1
    if count > 0:
        return True
    else:
        return False
# Original array
array = np.array([4,6,0,0,0,4,89])
print(array)
  
# Test whether any of the elements
# of a given array is non-zero
print(test(array))
print('#'*50)
print(np.any(array))

[ 4  6  0  0  0  4 89]
True
##################################################
True


# 3-Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given 

In [27]:
def tolerance(lst1,lst2):
    length = len(lst1)
    try:
        if length == len(lst2):
            count = 0
            for index,value in enumerate(lst1):
                if lst1[index] == lst2[index]:
                    count +=1
            if count == length:
                return True
            else:
                return False
    except Exception as e:
        print(e,'two lists are not equal in length')
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 70])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 70])
print("Original numbers:")
print(x)
print(y)
print('#'*50)
print("Comparison - equal:")
print(np.equal(x, y))
print('#'*50)
print("Comparison - equal within a tolerance:")
print(tolerance(x,y))
print('#'*50)
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Original numbers:
[  72   79   85   90  150 -135  120  -10   60   70]
[  72   79   85   90  150 -135  120  -10   60   70]
##################################################
Comparison - equal:
[ True  True  True  True  True  True  True  True  True  True]
##################################################
Comparison - equal within a tolerance:
True
##################################################
Comparison - equal within a tolerance:
True


# 4-Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.


In [32]:
def zero(num):
    lst = []
    for i in range(num):
        lst.append(0)
    return np.array(lst)
def one(num):
    lst = []
    for i in range(num):
        lst.append(1)
    return np.array(lst)
def five(num):
    lst = []
    for i in range(num):
        lst.append(5)
    return np.array(lst)
array = zero(10)
print("An array of 10 zeros:")
print(array)
print('#'*50)
array = np.zeros(10)
print("An array of 10 zeros:")
print(array)
print('#'*50)
array = one(10)
print("An array of 10 ones:")
print(array)
print('#'*50)
array = np.ones(10)
print("An array of 10 ones:")
print(array)
print('#'*50)
array = five(10)
print("An array of 10 fives:")
print(array)
print('#'*50)
array = np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0 0 0 0 0 0 0 0 0 0]
##################################################
An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
##################################################
An array of 10 ones:
[1 1 1 1 1 1 1 1 1 1]
##################################################
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
##################################################
An array of 10 fives:
[5 5 5 5 5 5 5 5 5 5]
##################################################
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# 5-Write a NumPy program to create an array of the integers from 30 to70.

In [35]:
def array():
    lst = []
    for i in range(30,71):
        lst.append(i)
    return np.array(lst)
print('Array of the integers from 30 to 70')
print(array())
print('#'*50)
array=np.arange(30,71)
print("Array of the integers from 30 to70")
print(array)

Array of the integers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
##################################################
Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


# 6-Write a NumPy program to create a 3x3 identity matrix 

In [47]:
def array_2Dim(num1,num2):
    lst1 = []
    lst2 = []
    for i in range(num1):
        for i2 in range(num2):
            lst1.append(i2*3)
        lst2.append(lst1)
        lst1 = []
    return np.array(lst2)
print('3*3 martix:')
array_2D = array_2Dim(3,3)
print(array_2D)
print('#'*50)
array_2D = np.identity(3)
print('3*3 matrix:')
print(array_2D)
print('#'*50)
print('4*4 matrix:')
array_2D = array_2Dim(4,4)
print(array_2D)
print('#'*50)
array_2D = np.identity(4)
print('4*4 matrix:')
print(array_2D)

3*3 martix:
[[0 3 6]
 [0 3 6]
 [0 3 6]]
##################################################
3*3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
##################################################
4*4 matrix:
[[0 3 6 9]
 [0 3 6 9]
 [0 3 6 9]
 [0 3 6 9]]
##################################################
4*4 matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 7-Write a NumPy program to generate a random number between 0 and 1 

In [74]:
def rand(num):
    num = num * 10
    num = num /1000
    return num
print("Random number between 0 and 1:")
print(rand(3))
rand_num = np.random.normal(0,1,1)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
0.03
Random number between 0 and 1:
[0.38524692]


# 8-Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution 

In [85]:
def rand(start,end,size):
    lst = []
    for i in range(size):
        num = ((i+start) * end)/100
        lst.append(num)
    return lst
print(rand(0,1,15))
print('#'*50)
rand_num = np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)

[0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13, 0.14]
##################################################
15 random numbers from a standard normal distribution:
[-1.64683196 -0.24958601 -0.75619767  0.02489204 -0.69558787  0.30031297
  1.21550768  0.32824629 -0.65951299 -1.22507676  0.36985136 -0.77754479
 -0.24239867 -0.63637475 -1.02551636]


# 9-Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.


In [88]:
def arange(start,end):
    lst = []
    for i in range(start+1,end-1):
        lst.append(i)
    return lst
print("All values except the first and last of the said vector:")
print(arange(15,55))
v = np.arange(15,55)
print("Original vector:")
print(v)
print("All values except the first and last of the said vector:")
print(v[1:-1])

All values except the first and last of the said vector:
[16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53]
Original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
All values except the first and last of the said vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


# 10-Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10 

In [107]:
def rand(start,end,size):
    lst = []
    for i in range(size):
        i = int(((end*0.55) - i+1) * 0.9)
        lst.append(i)
    return lst
print("Vector of length 5 filled with arbitrary integers from 0 to 10:")
print(rand(0,10,5))
print('#'*50)
x = np.random.randint(0, 11, 5)
print("Vector of length 5 filled with arbitrary integers from 0 to 10:")
print(x)

Vector of length 5 filled with arbitrary integers from 0 to 10:
[5, 4, 4, 3, 2]
##################################################
Vector of length 5 filled with arbitrary integers from 0 to 10:
[ 2 10  8  5  3]


# 11-Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1,and inside 0.

In [115]:
def array_2Dim(num1,num2):
    lst1 = []
    lst2 = []
    for i in range(num1):
        for i2 in range(num2):
            if i == 0:
                lst1.append(1)
            elif i == num1 - 1:
                lst1.append(1)
            elif i2 == 0:
                lst1.append(1)
            elif i2 == num2 - 1:
                lst1.append(1)
            else:
                lst1.append(0)
        lst2.append(lst1)
        lst1 = []
    return np.array(lst2)
print('10x10 matrix:')
print(array_2Dim(10,10))
print('#'*50)
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

10x10 matrix:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]
##################################################
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 12-Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [122]:
def array_2Dim(num1,num2):
    lst1 = []
    lst2 = []
    for i in range(num1):
        for i2 in range(num2):
            if  i2 == i:
                lst1.append(i+1)
            else:
                lst1.append(0)
        lst2.append(lst1)
        lst1 = []
    return np.array(lst2)
print(array_2Dim(5,5))
print('#'*50)
x = np.diag([1, 2, 3, 4, 5])
print(x)
print('#'*50)
print(array_2Dim(6,6))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
##################################################
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
##################################################
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


# 13-Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [169]:
def array_2Dim(num1,num2):
    lst1 = []
    lst2 = []
    for i in range(num1):
        for i2 in range(num2):
            if i2 == i:
                lst1.append(0)
            elif i2 == i+1:
                lst1.append(1)
            elif i == i2+1:
                lst1.append(1)
            elif (i2 + 1) == num2 and i == 0:
                lst1.append(1)
            elif i-num2+1 == 0 and i2 == 0:
                lst1.append(1)
            else:
                lst1.append(0)
        lst2.append(lst1)
        lst1 = []
    return np.array(lst2)
print(array_2Dim(4,4))
print('#'*50)
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]
##################################################
[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


# 14-Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [179]:
import os
def save(v1,v2,name):
    name = name+'.npz'
    np.savez(name,first_column = v1,seconed_column = v2)
def load(name):
    name = name + '.npz'
    with np.load(name) as data:
        v1 = data['first_column']
        v2 = data['seconed_column']
        print(v1)
        print(v2)
x = np.arange(10)
y = np.arange(11, 20)
print("Original arrays:")
print(x)
print(y)
print('#'*50)
print('load arrays from file')
save(x,y,'try')
load('try')
print('#'*50)
np.savez('temp_arra.npz', x=x, y=y)
print("Load arrays from the 'temp_arra.npz' file:")
with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(x2)
    print(y2)

Original arrays:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
##################################################
load arrays from file
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
##################################################
Load arrays from the 'temp_arra.npz' file:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


# 15-Write a NumPy program to create a one dimensional array of forty pseudo-randomly generated values. Select 

In [185]:
def rand(start,end,size):
    lst = []
    for i in range(size):
        i = (i+end*0.55) *0.9
        lst.append(i)
    return lst
print(rand(0,1,40))
print('#'*50)
np.random.seed(10)
print(np.random.rand(40))

[0.49500000000000005, 1.395, 2.295, 3.195, 4.095, 4.995, 5.895, 6.795, 7.695000000000001, 8.595, 9.495000000000001, 10.395000000000001, 11.295000000000002, 12.195, 13.095, 13.995000000000001, 14.895000000000001, 15.795000000000002, 16.695, 17.595000000000002, 18.495, 19.395, 20.295, 21.195, 22.095000000000002, 22.995, 23.895, 24.795, 25.695, 26.595000000000002, 27.495, 28.395, 29.294999999999998, 30.194999999999997, 31.095, 31.994999999999997, 32.894999999999996, 33.795, 34.695, 35.595]
##################################################
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715]


# 16-Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number

In [192]:
def greater(num,array):
    lst = []
    for nums in array:
        for i in nums:
            if i > num:
                lst.append(i)
    return lst
def less(num,array):
    lst = []
    for nums in array:
        for i in nums:
            if i < num:
                lst.append(i)
    return lst
array = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])
print("Original array:")
print(array)
print('#'*50)
print("Elements of the said array greater than",5)
print(greater(5,array))
print('#'*50)
print("Elements of the said array less than",6)
print(less(6,array))
print('#'*50)
n = 5
print("\nElements of the said array greater than",n)
print(nums[nums > n])
print('#'*50)
n = 6
print("\nElements of the said array less than",n)
print(nums[nums < n])

Original array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
##################################################
Elements of the said array greater than 5
[5.54, 7.99, 6.99, 9.29]
##################################################
Elements of the said array less than 6
[5.54, 3.38, 3.54, 4.38, 1.54, 2.39]
##################################################

Elements of the said array greater than 5
[5.54 7.99 6.99 9.29]
##################################################

Elements of the said array less than 6
[5.54 3.38 3.54 4.38 1.54 2.39]
